#######################################################################
### CXX: The name of the parallel c++ compiler
### MAKE: The name of make utility (use gmake for freebsd) ############
CXX = mpiCC
MAKE = make
CFLAGS = 
