# ifndef __PROTOCOL__H
# define __PROTOCOL__H

# define SERVER_ASKMINIMUM	101
# define SERVER_SENDMINIMUM	102
# define SERVER_TERMINATE	103
# define CLIENT_SEND_STATUS	104
# define CLIENT_SEND_MINIMUM	105
# define CLIENT_FINISHED	106
# define CLIENT_TAG_SEND	107
# define CLIENT_TAG_LENGTH	108
# define CLIENT_TAG_STR		109
# define CLIENT_TAG_TERMINATE	110
# define SERVER_TAG_MESSAGE	111
# define SERVER_ALLOW_TERMINATE	112

//messages
//tags
# define TAG_LENGTH		100
# define TAG_STR		101
# define TAG_CLIENT_MESSAGE	102
# define TAG_SERVER_MESSAGE	103
# endif
